type Query {
    ping: String!
}

type Mutation {
    registerUser(input: RegisterUserInput!) : User
    login(input: LoginInput!) : LoginResult
    requestPasswordReset(email: String!) : Boolean!
    resetPassword(input: ResetPasswordInput!) : Boolean!
}

input ResetPasswordInput {
    token: String!
    newPassword: String!
}

input LoginInput {
    email: String!
    password: String!
}

type LoginResult {
    user: User!
    token: String!
}

input RegisterUserInput {
    email: String!
    password: String!
}

type User {
    id: ID!
    email: String!
    active: Boolean!
}
